apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ben-boehmer/gitops-airgap-demo.git
    targetRevision: HEAD
    path: apps/hello-service/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
